packages:
  - packages/*

allowBuilds:
  '@julusian/freetype2': false

catalog:
  "@eslint/js": "^9.39.4"
  "@tsconfig/node22": "^22.0.5"
  "@types/debug": "^4.1.13"
  "@types/node": "^25.5.0"
  "atem-connection": "^3.9.0"
  debug: ^4.4.3
  "eslint": "^9.39.4"
  "exit-hook": "^5.1.0"
  socket.io: ^4.8.3
  socket.io-client: ^4.8.3
  "ts-node": "^10.9.2"
  "tsl-umd-v5": "github:MansfieldTX-MattR/tsl-umd-v5#multi-tally-messages"
  "typescript": "^6.0.2"
  "typescript-eslint": "^8.58.0"

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - "tsl-umd-v5"
