packages:
  - packages/*

allowBuilds:
  '@julusian/freetype2': false

catalog:
  "@eslint/js": "^9.39.4"
  '@trpc/client': ^11.16.0
  '@trpc/server': ^11.16.0
  "@tsconfig/node22": "^22.0.5"
  "@types/debug": "^4.1.13"
  "@types/node": "^25.5.0"
  '@types/ws': ^8.18.1
  "atem-connection": "^3.9.0"
  debug: ^4.4.3
  "eslint": "^9.39.4"
  "exit-hook": "^5.1.0"
  "ts-node": "^10.9.2"
  "tsl-umd-v5": "github:MansfieldTX-MattR/tsl-umd-v5#multi-tally-messages"
  "typescript": "^6.0.2"
  "typescript-eslint": "^8.58.0"
  ws: ^8.20.0
  zod: ^4.3.6

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - "tsl-umd-v5"
